classdef LoginScreen < handle
    % LoginScreen - 登录/模式选择界面
    %   显示系统标题和模式选择按钮，用户选择后返回模式标识

    properties (Access = private)
        UIFigure    matlab.ui.Figure
    end

    properties (SetAccess = private)
        SelectedMode    string = ""
    end

    methods
        function mode = show(obj)
            % show 构建登录界面并阻塞等待用户选择
            % 返回值: "model_validation" | "rehab_assessment" | "" (关闭窗口)

            import config.AppConstants

            % 居中窗口
            screenSize = get(0, 'ScreenSize');
            x = max(1, (screenSize(3) - AppConstants.LOGIN_WINDOW_WIDTH) / 2);
            y = max(1, (screenSize(4) - AppConstants.LOGIN_WINDOW_HEIGHT) / 2);

            obj.UIFigure = uifigure(...
                'Name', '肌电慧控', ...
                'Position', [x, y, AppConstants.LOGIN_WINDOW_WIDTH, AppConstants.LOGIN_WINDOW_HEIGHT], ...
                'Color', AppConstants.COLOR_BG, ...
                'Resize', 'on', ...
                'CloseRequestFcn', @(~,~) obj.onClose());

            obj.buildContent();
            uiwait(obj.UIFigure);
            mode = obj.SelectedMode;
        end
    end

    methods (Access = private)
        function buildContent(obj)
            import config.AppConstants

            % 主网格：标题、内容、底部
            mainGrid = uigridlayout(obj.UIFigure, [3, 1], ...
                'RowHeight', {'fit', '1x', 'fit'}, ...
                'Padding', [0, 0, 0, 0], ...
                'RowSpacing', 0, ...
                'BackgroundColor', AppConstants.COLOR_BG);

            % ---- 标题区域 ----
            titleGrid = uigridlayout(mainGrid, [3, 1], ...
                'RowHeight', {'fit', 'fit', 'fit'}, ...
                'Padding', [20, 16, 20, 4], ...
                'RowSpacing', 2, ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(titleGrid, ...
                'Text', '肌电慧控', ...
                'FontSize', 28, ...
                'FontWeight', 'bold', ...
                'FontColor', AppConstants.COLOR_PRIMARY, ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(titleGrid, ...
                'Text', '基于高密度肌电分解的腕关节运动解码与康复评估系统', ...
                'FontSize', AppConstants.FONT_SIZE_SMALL, ...
                'FontColor', AppConstants.COLOR_TEXT_LIGHT, ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(titleGrid, ...
                'Text', 'v1.0', ...
                'FontSize', 9, ...
                'FontColor', [0.7 0.7 0.7], ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            % ---- 内容区：左侧Logo + 右侧模式按钮 ----
            contentGrid = uigridlayout(mainGrid, [1, 2], ...
                'ColumnWidth', {'4x', '5x'}, ...
                'Padding', [24, 10, 24, 16], ...
                'ColumnSpacing', 24, ...
                'RowSpacing', 0, ...
                'BackgroundColor', AppConstants.COLOR_BG);

            % 左侧：Logo
            ax = uiaxes(contentGrid, 'Visible', 'off');
            ax.Layout.Row = 1;
            ax.Layout.Column = 1;

            logoFile = fullfile(fileparts(which('LoginScreen')), '使用工具生成图片.png');
            if exist(logoFile, 'file')
                [img, map, alpha] = imread(logoFile);
                if isempty(alpha)
                    imshow(img, map, 'Parent', ax);
                else
                    if isempty(map)
                        rgb = img;
                    else
                        rgb = ind2rgb(img, map);
                    end
                    image(rgb, 'Parent', ax, 'AlphaData', alpha);
                    ax.Visible = 'off';
                    axis(ax, 'image');
                end
            end

            % 右侧：模式选择按钮
            btnPanel = uigridlayout(contentGrid, [5, 1], ...
                'RowHeight', {'1x', 'fit', 54, 54, '1x'}, ...
                'Padding', [0, 0, 0, 0], ...
                'RowSpacing', 14, ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(btnPanel, 'Text', '', 'BackgroundColor', AppConstants.COLOR_BG, 'FontSize', 1);

            uilabel(btnPanel, ...
                'Text', '请选择系统模式', ...
                'FontSize', AppConstants.FONT_SIZE_HEADING, ...
                'FontColor', AppConstants.COLOR_TEXT, ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uibutton(btnPanel, 'push', ...
                'Text', '模型验证系统', ...
                'FontSize', 22, ...
                'FontWeight', 'bold', ...
                'FontName', AppConstants.FONT_NAME, ...
                'FontColor', [1 1 1], ...
                'BackgroundColor', AppConstants.COLOR_PRIMARY, ...
                'ButtonPushedFcn', @(~,~) obj.onModeSelected('model_validation'));

            uibutton(btnPanel, 'push', ...
                'Text', '康复评估系统', ...
                'FontSize', 22, ...
                'FontWeight', 'bold', ...
                'FontName', AppConstants.FONT_NAME, ...
                'FontColor', [1 1 1], ...
                'BackgroundColor', AppConstants.COLOR_SECONDARY, ...
                'ButtonPushedFcn', @(~,~) obj.onModeSelected('rehab_assessment'));

            uilabel(btnPanel, 'Text', '', 'BackgroundColor', AppConstants.COLOR_BG, 'FontSize', 1);

            % ---- 底部区域 ----
            bottomGrid = uigridlayout(mainGrid, [1, 1], ...
                'Padding', [10, 8, 10, 8], ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(bottomGrid, ...
                'Text', [char(169), ' 2026 肌电慧控项目组'], ...
                'FontSize', AppConstants.FONT_SIZE_SMALL, ...
                'FontColor', [0.8 0.8 0.8], ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);
        end

        function onModeSelected(obj, mode)
            obj.SelectedMode = mode;
            uiresume(obj.UIFigure);
            if isvalid(obj.UIFigure)
                delete(obj.UIFigure);
            end
        end

        function onClose(obj)
            obj.SelectedMode = "";
            uiresume(obj.UIFigure);
            if isvalid(obj.UIFigure)
                delete(obj.UIFigure);
            end
        end
    end
end
