classdef LoginScreen < handle
    % LoginScreen - 登录/模式选择界面
    %   显示系统标题和模式选择按钮，用户选择后返回模式标识

    properties (Access = private)
        UIFigure    matlab.ui.Figure
    end

    properties (SetAccess = private)
        SelectedMode    string = ""
    end

    methods
        function mode = show(obj)
            % show 构建登录界面并阻塞等待用户选择
            % 返回值: "model_validation" | "rehab_assessment" | "" (关闭窗口)

            import config.AppConstants

            % 居中窗口
            screenSize = get(0, 'ScreenSize');
            x = max(1, (screenSize(3) - AppConstants.WINDOW_WIDTH) / 2);
            y = max(1, (screenSize(4) - AppConstants.WINDOW_HEIGHT) / 2);

            obj.UIFigure = uifigure(...
                'Name', '肌电慧控', ...
                'Position', [x, y, AppConstants.WINDOW_WIDTH, AppConstants.WINDOW_HEIGHT], ...
                'Color', AppConstants.COLOR_BG, ...
                'Resize', 'on', ...
                'CloseRequestFcn', @(~,~) obj.onClose());

            obj.buildContent();
            uiwait(obj.UIFigure);
            mode = obj.SelectedMode;
        end
    end

    methods (Access = private)
        function buildContent(obj)
            import config.AppConstants

            % 主网格：上中下三行
            mainGrid = uigridlayout(obj.UIFigure, [3, 1], ...
                'RowHeight', {'2x', '3x', '1x'}, ...
                'Padding', [0, 0, 0, 0], ...
                'RowSpacing', 0, ...
                'BackgroundColor', AppConstants.COLOR_BG);

            % ---- 标题区域 ----
            titleGrid = uigridlayout(mainGrid, [4, 1], ...
                'RowHeight', {'1x', 'fit', 'fit', 'fit'}, ...
                'Padding', [20, 10, 20, 10], ...
                'RowSpacing', 2, ...
                'BackgroundColor', AppConstants.COLOR_BG);

            % 占位弹簧
            uilabel(titleGrid, 'Text', '', 'BackgroundColor', AppConstants.COLOR_BG, 'FontSize', 1);

            uilabel(titleGrid, ...
                'Text', '肌电慧控', ...
                'FontSize', 42, ...
                'FontWeight', 'bold', ...
                'FontColor', AppConstants.COLOR_PRIMARY, ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(titleGrid, ...
                'Text', '基于高密度肌电分解的腕关节运动解码与康复评估系统', ...
                'FontSize', AppConstants.FONT_SIZE_HEADING, ...
                'FontColor', AppConstants.COLOR_TEXT_LIGHT, ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(titleGrid, ...
                'Text', 'v1.0', ...
                'FontSize', AppConstants.FONT_SIZE_SMALL, ...
                'FontColor', [0.7 0.7 0.7], ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);

            % ---- 分隔线 + 按钮区域 ----
            btnGrid = uigridlayout(mainGrid, [3, 1], ...
                'RowHeight', {'fit', 'fit', '1x'}, ...
                'Padding', [0, 20, 0, 20], ...
                'RowSpacing', 0, ...
                'BackgroundColor', [0.90 0.93 0.96]);

            % 提示文字
            uilabel(btnGrid, ...
                'Text', '请选择系统模式', ...
                'FontSize', AppConstants.FONT_SIZE_HEADING, ...
                'FontColor', AppConstants.COLOR_TEXT, ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.90 0.93 0.96]);

            % 按钮行
            btnRow = uigridlayout(btnGrid, [1, 4], ...
                'ColumnWidth', {'1x', 280, 280, '1x'}, ...
                'Padding', [10, 10, 10, 10], ...
                'ColumnSpacing', 40, ...
                'RowSpacing', 0, ...
                'BackgroundColor', [0.90 0.93 0.96]);

            uilabel(btnRow, 'Text', '', 'BackgroundColor', [0.90 0.93 0.96], 'FontSize', 1);

            % 模型验证系统按钮
            mvBtn = uibutton(btnRow, 'push', ...
                'Text', '模型验证系统', ...
                'FontSize', 20, ...
                'FontWeight', 'bold', ...
                'FontName', AppConstants.FONT_NAME, ...
                'FontColor', [1 1 1], ...
                'BackgroundColor', AppConstants.COLOR_PRIMARY, ...
                'ButtonPushedFcn', @(~,~) obj.onModeSelected('model_validation'));
            mvBtn.Layout.Row = 1;
            mvBtn.Layout.Column = 2;

            % 康复评估系统按钮
            reBtn = uibutton(btnRow, 'push', ...
                'Text', '康复评估系统', ...
                'FontSize', 20, ...
                'FontWeight', 'bold', ...
                'FontName', AppConstants.FONT_NAME, ...
                'FontColor', [1 1 1], ...
                'BackgroundColor', AppConstants.COLOR_SECONDARY, ...
                'ButtonPushedFcn', @(~,~) obj.onModeSelected('rehab_assessment'));
            reBtn.Layout.Row = 1;
            reBtn.Layout.Column = 3;

            uilabel(btnRow, 'Text', '', 'BackgroundColor', [0.90 0.93 0.96], 'FontSize', 1);

            % 弹簧
            uilabel(btnGrid, 'Text', '', 'BackgroundColor', [0.90 0.93 0.96], 'FontSize', 1);

            % ---- 底部区域 ----
            bottomGrid = uigridlayout(mainGrid, [1, 1], ...
                'Padding', [10, 10, 10, 10], ...
                'BackgroundColor', AppConstants.COLOR_BG);

            uilabel(bottomGrid, ...
                'Text', [char(169), ' 2026 肌电慧控项目组'], ...
                'FontSize', AppConstants.FONT_SIZE_SMALL, ...
                'FontColor', [0.8 0.8 0.8], ...
                'FontName', AppConstants.FONT_NAME, ...
                'HorizontalAlignment', 'center', ...
                'BackgroundColor', AppConstants.COLOR_BG);
        end

        function onModeSelected(obj, mode)
            obj.SelectedMode = mode;
            uiresume(obj.UIFigure);
            if isvalid(obj.UIFigure)
                delete(obj.UIFigure);
            end
        end

        function onClose(obj)
            obj.SelectedMode = "";
            uiresume(obj.UIFigure);
            if isvalid(obj.UIFigure)
                delete(obj.UIFigure);
            end
        end
    end
end
