# -*- mode: python ; coding: utf-8 -*-

import sys
sys.setrecursionlimit(5000)

block_cipher = None

a = Analysis(
    [r'..\decompose_python_bridge.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'sklearn',
        'sklearn.decomposition',
        'sklearn.decomposition._fastica',
        'sklearn.utils',
        'sklearn.utils._joblib',
        'sklearn.utils._cython_blas',
        'sklearn.utils.arrayfuncs',
        'sklearn.utils._fast_dict',
        'sklearn.utils._openmp_helpers',
        'sklearn.utils.weight_vector',
        'sklearn.utils.seq_dataset',
        'sklearn.utils.random',
        'sklearn.linear_model',
        'sklearn.linear_model.cd_fast',
        'sklearn.linear_model.sag_fast',
        'sklearn.linear_model.sgd_fast',
        'sklearn.tree._tree',
        'sklearn.tree._splitter',
        'sklearn.tree._criterion',
        'sklearn.neighbors.ball_tree',
        'sklearn.neighbors.kd_tree',
        'sklearn.neighbors.dist_metrics',
        'sklearn.neighbors.typedefs',
        'sklearn.metrics.cluster.expected_mutual_info_fast',
        'sklearn.cluster._k_means_elkan',
        'sklearn.svm.libsvm',
        'sklearn.svm.liblinear',
        'sklearn.svm.libsvm_sparse',
        'scipy',
        'scipy.io',
        'scipy.linalg',
        'scipy.sparse',
        'scipy.sparse.linalg',
        'scipy.sparse.csgraph',
        'h5py',
        'h5py._errors',
        'h5py.defs',
        'h5py.utils',
        'h5py.h5ac',
        'h5py._proxy',
        'numpy',
        'numpy.core',
        'numpy.random',
        'numpy.linalg',
        'pandas',
        'joblib',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'IPython',
        'jupyter',
        'notebook',
        'tkinter',
        'PyQt5',
        'sqlalchemy',
        'PIL',
        'pygments',
        'pytest',
        'setuptools',
        'pip',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='decompose_python_bridge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
