classdef ExportDialog
    % ExportDialog - 导出选项弹窗

    methods (Static)
        function show(parent, mainApp)
            import config.AppConstants

            dlg = uifigure('Name', '导出选项', ...
                'Position', [500, 400, 350, 400], ...
                'Resize', 'off', 'WindowStyle', 'modal');

            grid = uigridlayout(dlg, [7, 1], ...
                'Padding', [20, 20, 20, 20], ...
                'RowSpacing', 10);

            uilabel(grid, 'Text', '选择导出内容:', ...
                'FontName', AppConstants.FONT_NAME, ...
                'FontSize', AppConstants.FONT_SIZE_HEADING, ...
                'FontWeight', 'bold');

            cbRaw = uicheckbox(grid, 'Text', '原始EMG数据 (.mat)', 'Value', true, ...
                'FontName', AppConstants.FONT_NAME);
            cbSpike = uicheckbox(grid, 'Text', 'MU发放序列 (.csv)', 'Value', true, ...
                'FontName', AppConstants.FONT_NAME);
            cbPred = uicheckbox(grid, 'Text', '预测结果 - 角度+力 (.csv)', 'Value', true, ...
                'FontName', AppConstants.FONT_NAME);
            cbReport = uicheckbox(grid, 'Text', '评估报告 (.html)', 'Value', true, ...
                'FontName', AppConstants.FONT_NAME);
            cbFig = uicheckbox(grid, 'Text', '图表截图 (.png)', 'Value', false, ...
                'FontName', AppConstants.FONT_NAME);

            btnGrid = uigridlayout(grid, [1, 2]);
            uibutton(btnGrid, 'Text', '导出', ...
                'BackgroundColor', AppConstants.COLOR_PRIMARY, ...
                'FontColor', [1 1 1], 'FontName', AppConstants.FONT_NAME, ...
                'ButtonPushedFcn', @(~,~) ExportDialog.doExport(dlg, mainApp, ...
                cbRaw.Value, cbSpike.Value, cbPred.Value, cbReport.Value, cbFig.Value));
            uibutton(btnGrid, 'Text', '取消', 'FontName', AppConstants.FONT_NAME, ...
                'ButtonPushedFcn', 'delete(gcbf)');
        end

        function doExport(dlg, mainApp, exportRaw, exportSpike, exportPred, exportReport, exportFig)
            selPath = uigetdir(pwd, '选择导出目录');
            if selPath == 0
                uialert(dlg, '请选择导出目录', '取消', 'Icon', 'info');
                return;
            end

            try
                if exportRaw && ~isempty(mainApp.RawEmgData)
                    services.DataExportService.saveFullData(...
                        fullfile(selPath, 'raw_data.mat'), ...
                        mainApp.RawEmgData, mainApp.Fs, ...
                        mainApp.SpikeTrainMatrix, ...
                        mainApp.FeatureMatrix, mainApp.TimeVector, ...
                        mainApp.PredictedAngle, mainApp.PredictedForce, ...
                        mainApp.GroundTruthAngle, mainApp.GroundTruthForce, ...
                        mainApp.CurrentSession);
                end

                if exportSpike && ~isempty(mainApp.SpikeTrainMatrix)
                    services.DataExportService.exportSpikeTrainsCSV(...
                        mainApp.SpikeTrainMatrix, mainApp.Fs, ...
                        mainApp.TimeVector, fullfile(selPath, 'spike_trains.csv'));
                end

                if exportPred && ~isempty(mainApp.PredictedAngle)
                    services.DataExportService.exportPredictionCSV(...
                        mainApp.TimeVector, ...
                        mainApp.PredictedAngle, mainApp.GroundTruthAngle, ...
                        mainApp.PredictedForce, mainApp.GroundTruthForce, ...
                        fullfile(selPath, 'prediction_results.csv'));
                end

                if exportReport && ~isempty(mainApp.AssessmentResults)
                    services.DataExportService.exportReportHTML(...
                        mainApp.AssessmentResults, mainApp.CurrentPatient, ...
                        fullfile(selPath, 'assessment_report.html'));
                end

                mainApp.log(sprintf('批量导出完成: %s', selPath));
                uialert(dlg, sprintf('导出成功!\n目录: %s', selPath), '导出成功', 'Icon', 'success');
                delete(dlg);
            catch e
                uialert(dlg, sprintf('导出失败: %s', e.message), '错误', 'Icon', 'error');
            end
        end
    end
end
